In [1]:
import os
import pandas as pd
import numpy as np
import math
list = []
namelist = []
valuelist = []
positive = 0 
negative = 0
sum_pos = 0
sum_neg = 0
rankinglist = []
for file in os.listdir("C:\\Users\\User\\Desktop\\ETFF"):
    name = "C:\\Users\\User\\Desktop\\ETFF"+"\\"+file
    list.append(name)
    namelist.append(file.split(".")[0])
def omega(r):
    rf = math.pow((1+0.02822), 1/52)-1
    if r >= 0:
        ans = r - rf
    else:
        ans = r + rf
    return ans

for i in list:
    rw=[]
    df = pd.read_csv(i)
    df = df.replace(r'^\s*$', np.nan, regex=True)
    for j in df["return_week"]:
        if j != "NaN":
            rw.append(omega(j))
        else: 
            rw.append(0)
    df["return_week1"] = rw
    for i in df['return_week1']:
        if i >0:
            positive += i
            sum_pos += 1
        else:
            negative -= i
            sum_neg +=1
    valuelist.append(sum_pos/sum_neg)
c = {'ETF_symbol':namelist,'Value':valuelist}
new = pd.DataFrame(c)
result = new.sort_values(by=['Value'], ascending=False)
result1= result.iloc[1:]
result2 = result1.assign(Rankimg =df.a.mean())
result1

   ETF_symbol     Value
31        RTH  1.154846
30        RGI  1.148291
28        RCD  1.142228
29       RETL  1.142193
25        PPA  1.141371
26       PSCD  1.139611
27       PSCI  1.138887
46       _PRN  1.138714
45        XTN  1.137448
43        XLY  1.136343
44        XRT  1.136042
33        SCC  1.135019
23        PIO  1.134581
42        XLI  1.132436
24        PMR  1.132240
22        PHO  1.131312
41        XAR  1.129647
21        PEZ  1.128737
39        VIS  1.125749
19        PBS  1.125348
20        PEJ  1.124729
34        SEA  1.124385
40       WBIA  1.124185
38        VCR  1.122142
18        IYT  1.119440
37        UXI  1.116952
17        IYJ  1.114491
36        UCC  1.112754
35        SIJ  1.109322
16        IYC  1.102977
15        ITA  1.089306
3         CGW  1.069022
14       INCO  1.068799
5        CHIQ  1.058599
13        IEV  1.058274
12        FXR  1.056805
4        CHII  1.052168
11        FXD  1.042314
2        CARZ  1.037217
0        AIRR  1.033926
10        FIW  1.027229
1         BJK  1.014400
9        FIDU  1.012630
8        FDIS  0.990513
7         EXI  0.954395
6         EVX  0.915236