In [1]:
import os
import pandas as pd
import numpy as np
import math
list = []
namelist = []
valuelist = []
positive = 0 
negative = 0
sum_pos = 0
sum_neg = 0
rankinglist = []
for file in os.listdir("C:\\Users\\User\\Desktop\\ETFF"):
    name = "C:\\Users\\User\\Desktop\\ETFF"+"\\"+file
    list.append(name)
    namelist.append(file.split(".")[0])
def omega(r):
    rf = math.pow((1+0.02822), 1/12)-1
    if r >= 0:
        ans = r - rf
    else:
        ans = r + rf
    return ans

for i in list:
    rw=[]
    df = pd.read_csv(i)
    df = df.replace(r'^\s*$', np.nan, regex=True)
    for j in df["return_month"]:
        if j != "NaN":
            rw.append(omega(j))
        else: 
            rw.append(0)
    df["return_month1"] = rw
    for i in df['return_month1']:
        if i >0:
            positive += i
            sum_pos += 1
        else:
            negative -= i
            sum_neg +=1
    valuelist.append(sum_pos/sum_neg)
c = {'ETF_symbol':namelist,'Value':valuelist}
new = pd.DataFrame(c)
result = new.sort_values(by=['Value'], ascending=False)
result1= result.iloc[1:]
result1

   ETF_symbol     Value
32        RXI  1.238711
31        RTH  1.231349
25        PPA  1.223256
22        PHO  1.222086
30        RGI  1.221286
23        PIO  1.221201
26       PSCD  1.220538
28        RCD  1.219858
27       PSCI  1.218719
29       RETL  1.218574
21        PEZ  1.217356
19        PBS  1.214512
24        PMR  1.213206
20        PEJ  1.212570
18        IYT  1.208884
33        SCC  1.207240
46       _PRN  1.205111
45        XTN  1.204514
43        XLY  1.204235
44        XRT  1.203275
17        IYJ  1.203092
42        XLI  1.193746
39        VIS  1.192954
16        IYC  1.191032
38        VCR  1.190986
41        XAR  1.190658
34        SEA  1.188211
40       WBIA  1.186128
37        UXI  1.180438
36        UCC  1.175204
15        ITA  1.165681
35        SIJ  1.164009
5        CHIQ  1.148180
14       INCO  1.145665
4        CHII  1.137908
3         CGW  1.130288
12        FXR  1.127665
13        IEV  1.123494
11        FXD  1.118200
10        FIW  1.106801
9        FIDU  1.093630
1         BJK  1.093101
8        FDIS  1.071298
2        CARZ  1.068456
7         EXI  1.010581
6         EVX  0.966964